source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

post_install do |installer|  
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|  
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'  
    end  
end

target ‘JingChengDiningHall’ do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.7.5’
    pod 'AZSClient', '~> 0.2.2'
end